application: the-micro-manager
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /.*
  script: main.app
  secure: always

- url: /www/assets
  static_dir: assets

builtins:
- deferred: on